### ISSUE TITLE
Add Vanish?

### ISSUE THREAD

**Issue by ncrecc** [plasmaster09/Better-BR-Jester#5]
ncrmod has an alt version of vanish and ncr_vanish where there's a 50% chance for a random available dice of yourss to disappear whenever you use any equipment. Vanish? never goes away, ncr Vanish? decrements by 1 every time a dice is vanished. To fully emulate ncr this should be added. It's very simple and can be implemented based on that description alone, though you might need to do that "actuator that removes the status a split second after it's called" trick for alt vanish if terry hasn't fixed that crash yet

**Comment by plasmaster09** [comment]
would add those quickly and easily by porting them straight from ncrmod... but I can't find those in the files of the version of it I have, and ncrmod's itch page seems to have been tactically nuked of actual downloadable files

**Comment by ncrecc** [comment]
latest version of ncrmod is buried deep in a zipped passworded folder right now lol. like i said it should be recreatable from description alone. on any equipment use just pick a random available() dice from the dicepool and animate vanish on it

**Comment by plasmaster09** [comment]
done
